parameters:
#    bangpound_corp_watch_data.example.class: Bangpound\CorpWatch\DataBundle\Example

services:
#    bangpound_corp_watch_data.example:
#        class: %bangpound_corp_watch_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
